### ISSUE TITLE
Not able to open app protocol URLs in Aardvark.

### ISSUE THREAD

**Issue by JaredMonkey** [aardvarkxr/aardvark#73]
Trying to hook up an aardvark app that can open an app protocol such as pluto://rich-presence-update/ and I'm encountering an issue where I think that it isn't able to open because CEF is blocking app URLs.

**Comment by JoeLudwig** [comment]
How were you opening the app protocol URL? Can you include the line of code in the bug?

**Comment by JaredMonkey** [comment]
I was using using this link to test. 

<a href="pluto://rich-presence-update/%7B%22shareWebApp%22%3A%22aardvark%3A%2F%2Finstall%2Fhttp%3A%2F%2Ftinyurl.com%2Frfehyeu%22%7D”> Submit Rich Presence Update</a>

**Comment by JoeLudwig** [comment]
This should work now (though you'll want a target on that a tag to avoid nuking your gadget.)

There's an assert/exception/crash on shutdown in debug that's caused by the window that appears briefly when you do this. I'm trying to sort through that with the CEF folks: https://magpcss.org/ceforum/viewtopic.php?f=6&t=17314#p44306
